version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=nestjs_demo
      - JWT_SECRET=your_jwt_secret_key
    volumes:
      - ./src:/app/src
    networks:
      - app-network
    command: >
      sh -c "
        echo 'Waiting for MySQL to be ready...'
        while ! nc -z db 3306; do
          sleep 1
        done
        echo 'MySQL is ready!'
        npm run start:prod
      "

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=nestjs_demo
    volumes:
      - db-data:/var/lib/mysql
      - ./db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
